build: false  # Not a C# project
environment:
  matrix:
    - PY_VER: "36"
      ENV: "py"

matrix:
  fast_finish: true

install:
  - set PATH=C:\\Python%PY_VER%;%PATH%
  - python.exe  -m pip install -U .

test_script:
  - python.exe -m pip list --format=columns
  - python.exe -m tox3 -vvvv -e %ENV%


after_test:
  - set CODECOV_ENV=%ENV%-%PY_VER%
  - python.exe -m tox3 -vvvv -e codecov

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
