sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7-dev
  - nightly
env:
  TASK=test

matrix:
  fast_finish: true
  allow_failures:
  - os:  osx
  - python: 3.7-dev
  - python: nightly
  include:
    - python: 3.6
      TASK: TASK=type
    - python: 3.6
      TASK: TASK=doc

install:
  - pip install .

script:
  - pip list --format=columns
  - python -m toxn -v DEBUG -t $TASK
  
after_success:
  - export CODECOV_TASK="$TASK-$TRAVIS_PYTHON_VERSION"
  - if [[ $TASK == "py" ]]; then python -m toxn -v DEBUG -t codecov; fi
