sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7-dev
  - nightly
env:
  TOXENV=py

matrix:
  fast_finish: true
  allow_failures:
  - os:  osx
  - python: 3.7-dev
  - python: nightly
  include:
    - python: 3.6
      env: TOXENV=type
    
install:
  - pip install .

script:
  - pip list --format=columns
  - python -m tox3 -vvvv
