sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7-dev
  - nightly
env:
  ENV=py

matrix:
  fast_finish: true
  allow_failures:
  - os:  osx
  - python: 3.7-dev
  - python: nightly
  include:
    - python: 3.6
      env: ENV=type
    - python: 3.6
      env: ENV=doc

install:
  - pip install .

script:
  - pip list --format=columns
  - python -m toxn -v DEBUG -e $ENV
  
after_success:
  - export CODECOV_ENV="$ENV-$TRAVIS_PYTHON_VERSION"
  - if [[ $ENV == "py" ]]; then python -m toxn -v DEBUG -e codecov; fi
