build: false  # Not a C# project
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py"
      TOX_BUILD_PY: "py"

matrix:
  fast_finish: true

install:
  - set PATH=%PYTHON%;%PATH%
  - python.exe  -m pip install -U .

test_script:
  - python.exe -m pip list --format=columns
  - python.exe -m tox3 -vvvv"

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
