[build-system]
requires = ['setuptools >= 38.2.4']
build-backend = 'setuptools:build_meta'

[tool.tox3]
    envlist = ['py36', 'py35']

    [tool.tox3.env]
        basepython = 'python3.6'
        description = 'run the unit tests with pytest under {basepython}'
        commands = ["python -c \"import sys; print(sys.executable, sys.version)\" "]

    [tool.tox3.env._build]
        basepython = 'python3.6'

    [tool.tox3.env.py36]
        basepython = 'python3.6'

    [tool.tox3.env.py35]
        basepython = 'python3.5'
