from setuptools import setup

setuptools.setup(
    name='tox',
    description='virtualenv-based automation of test activities',
    long_description=get_long_description(),
    url='https://tox.readthedocs.org/',
    use_scm_version=True,
    license='http://opensource.org/licenses/MIT',
    platforms=['unix', 'linux', 'osx', 'cygwin', 'win32'],
    author='holger krekel',
    author_email='holger@merlinux.eu',
    packages=['tox'],
    entry_points={'console_scripts': ['tox=tox:cmdline',
                                      'tox-quickstart=tox._quickstart:main']},
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
    setup_requires=['setuptools_scm'],
    install_requires=['toml >= 0.9.3, <1'],
    extras_require={'testing': ['pytest >= 3.0.0',
                                'pytest-cov',
                                'pytest-timeout',
                                'pytest-xdist'],
                    'docs': ['sphinx >= 1.6.3, < 2',
                             'towncrier >= 17.8.0'],
                    'lint': ['flake8 == 3.4.1',
                             'flake8-bugbear == 17.4.0',
                             'pre-commit == 1.3.0'],
                    'publish': ['devpi',
                                'twine']},
    classifiers=['Development Status :: 5 - Production/Stable',
                 'Intended Audience :: Developers',
                 'License :: OSI Approved :: MIT License',
                 'Operating System :: POSIX',
                 'Operating System :: Microsoft :: Windows',
                 'Operating System :: MacOS :: MacOS X',
                 'Topic :: Software Development :: Testing',
                 'Topic :: Software Development :: Libraries',
                 'Topic :: Utilities'] + [
                    ('Programming Language :: Python :: {}'.format(x)) for x in '3.4 3.5 3.6'.split()]
)
