"""configuration objects

these are a join of user provided inputs:
- cli
- environment variable
- tox config file
and generated by the running of these tool (referred to as state).

"""
from pathlib import Path
from typing import List, Union, IO

from .state import BuildEnvConfig as StateBuildEnvConfig
from .state import RunEnvConfig as StateRunEnvConfig
from .state import ToxConfig as StateToxConfig
from .static import BuildEnvConfig as StaticBuildEnvConfig
from .static import RunEnvConfig as StaticRunEnvConfig
from .static import ToxConfig as StaticToxConfig
from .static.cli import parse
from .static.project import from_toml


class ToxConfig(StaticToxConfig, StateToxConfig):
    pass


class RunEnvConfig(StaticRunEnvConfig, StateRunEnvConfig):
    pass


class BuildEnvConfig(StaticBuildEnvConfig, StateBuildEnvConfig):
    pass


async def load(argv: List[str]) -> ToxConfig:
    options = await parse(argv)
    config_file: Union[Path, IO[str]] = options.__getattribute__('config')
    build_system, file = await from_toml(config_file)
    return ToxConfig(options, build_system, file)
