"""configuration objects

these are a join of user provided inputs:
- cli
- environment variable
- tox config file
and generated by the running of these tool (referred to as state).
"""
from pathlib import Path
from typing import IO, Sequence, Union

from tox3.config.models.core import root_dir
from .cli import parse
from .models.env_build import BuildEnvConfig
from .models.env_run import RunEnvConfig
from .models.tox import ToxConfig
from .project import BuildSystem, FileConf, from_toml
from .util import Substitute


async def load(argv: Sequence[str]) -> ToxConfig:
    options = await parse(argv)
    config_file: Union[Path, IO[str]] = options.__getattribute__('config')
    build_system, file = await from_toml(config_file)
    work_dir = root_dir(options, file.get('work_dir'))
    return ToxConfig(options, build_system, file, work_dir)


__all__ = ('ToxConfig', 'RunEnvConfig', 'BuildEnvConfig', 'load')
