""" configuration generated by running this tool"""
from pathlib import Path
from typing import Optional

""" holds all configuration information - input entries and runtime generated (states)"""


class State:
    pass


class CoreToxConfig(State):
    pass


class ToxConfig(CoreToxConfig):
    pass


class EnvConfig(CoreToxConfig):
    pass


class RunEnvConfig(EnvConfig):
    pass


class BuildEnvConfig(EnvConfig):
    _built_package: Optional[Path] = None

    @property
    def built_package(self) -> Optional[Path]:
        return self._built_package

    @built_package.setter
    def built_package(self, value: Path):
        self._built_package = value
